# Change these first
owner: Dwaris # Your GitHub username
repo: itclowd-uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Website
    url: https://itclowd.de
  - name: Nextcloud
    url: https://nextcloud.itclowd.de
    icon: https://nextcloud.com/wp-content/themes/next/assets/img/common/favicon.png?x53054
#  - name: HedgeDoc
#    url: https://pad.itclowd.de
#    icon: https://hedgedoc.org/icons/favicon-32x32.png
  - name: Matrix Homeserver
    url: https://matrix.itclowd.de/_matrix/federation/v1/version
    icon: https://element.io/images/favicon.png
    method: GET
    headers:
      - "Content-Type: application/json"
    body: '{ "name": "Synapse" }'

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.itclowd.de
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status of ITClowd
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
